//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public string CusID { get; set; }
        public Nullable<int> CLID { get; set; }
        public string CusName { get; set; }
        public string CusCompany { get; set; }
        public string CusMan { get; set; }
        public string CusDesc { get; set; }
    }
}
